# -*- coding: utf-8 -*-
"""StudentsPerformance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CpLuIhkpfLIm_QDIywHL2e8h3avY6q1P

* Are female students performing better than male students in <given subject> (you will take an input of subject and work on the course selected in options) 
* Are students that have done preparation courses are good in courses or not.
* What is the impact of parent education in student performance good, bad, or no impact ( your answer will be based on computational support, not verbal judgment)
"""

# Input Data
labels = ('gender', 'parental level of education', 'test preparation course', 'math score', 'reading score', 'writing score')
data = [ 
   ['female', "bachelor's degree", 'none', '72', '72', '74'], 
  ['female', 'some college', 'completed', '69', '90', '88'], 
  ['female', "master's degree", 'none', '90', '95', '93'], 
  ['male', "associate's degree", 'none', '47', '57', '44'], 
  ['male', 'some college', 'none', '76', '78', '75'], 
  ['female', "associate's degree", 'none', '71', '83', '78'], 
  ['female', 'some college', 'completed', '88', '95', '92'], 
  ['male', 'some college', 'none', '40', '43', '39'], 
  ['male', 'high school', 'completed', '64', '64', '67'], 
  ['female', 'high school', 'none', '38', '60', '50'], 
  ['male', "associate's degree", 'none', '58', '54', '52'], 
 ['male', "associate's degree", 'none', '40', '52', '43'], 
 ['female', 'high school', 'none', '65', '81', '73'], 
 ['male', 'some college', 'completed', '78', '72', '70'], 
 ['female', "master's degree", 'none', '50', '53', '58'], 
 ['female', 'some high school', 'none', '69', '75', '78'], 
 ['male', 'high school', 'none', '88', '89', '86'], 
 ['female', 'some high school', 'none', '18', '32', '28'], 
 ['male', "master's degree", 'completed', '46', '42', '46'], 
 ['female', "associate's degree", 'none', '54', '58', '61'], 
 ['male', 'high school', 'none', '66', '69', '63'], 
 ['female', 'some college', 'completed', '65', '75', '70'], 
 ['male', 'some college', 'none', '44', '54', '53'], 
 ['female', 'some high school', 'none', '69', '73', '73'], 
 ['male', "bachelor's degree", 'completed', '74', '71', '80'], 
 ['male', "master's degree", 'none', '73', '74', '72'], 
 ['male', 'some college', 'none', '69', '54', '55'], 
 ['female', "bachelor's degree", 'none', '67', '69', '75'], 
 ['male', 'high school', 'none', '70', '70', '65'], 
 ['female', "master's degree", 'none', '62', '70', '75'], 
 ['female', 'some college', 'none', '69', '74', '74'], 
 ['female', 'some college', 'none', '63', '65', '61'], 
 ['female', "master's degree", 'none', '56', '72', '65'], 
 ['male', 's6ome college', 'none', '40', '42', '38'], 
 ['male', 'some college', 'none', '97', '87', '82'], 
 ['male', "associate's degree", 'completed', '81', '81', '79'], 
 ['female', "associate's degree", 'none', '74', '81', '83'], 
 ['female', 'some high school', 'none', '50', '64', '59'], 
 ['female', "associate's degree", 'completed', '75', '90', '88'], 
]

"""## 1.   Are female students performing better than male students in (you will take an input of subject and work on the course selected in options)"""

def Perc_of_Gender(records,labels, gender, subject):
    percentage = 0
    count = 0
    sum = 0
    index_gender = labels.index("gender")
    index_subject = labels.index(subject)
    for r in [i for i in records if i[index_gender] == gender]:
        sum += int(r[index_subject])
        count += 1

    return round(float(sum / count),2) 

subject = input(f"Performace based on the gender in the subject\n{labels[-3:]}\n:")
#subject = "math score"
male_perc = Perc_of_Gender(data,labels,"male",subject)
female_perc = Perc_of_Gender(data,labels,"female",subject)
if male_perc > female_perc:
    print(f"Male students have performed better in {subject} than female ones, their % are\nmale: {male_perc} % female: {female_perc} %")
elif male_perc < female_perc:
    print(f"female students have performed better in {subject} than male ones, their % are\nmale: {male_perc} % female: {female_perc} %")
else:
    print(f"male and female students have performed equally  in {subject} , their % are\nmale: {male_perc} % female: {female_perc} %")

"""# 2.   Are students that have done preparation courses are good in courses or not?"""

def per_x_prep(records, labels):
    scores = 0
    count = 0
    index_test_prep = labels.index('test preparation course')
    for r in [row for row in records if row[index_test_prep] != "none"]:
        scores += sum([int(i) for i in r[-3:]])
        count += 3
    return round(float(scores/count),2)

test_prep_perc = per_x_prep(data,labels)
if test_prep_perc >= 80:
    print(f"Students who completed test prepration courses are doing good. their % is: {test_prep_perc}")
elif test_prep_perc >= 60:
    print(f"Students who completed test prepration courses are doing \"Ok\" their % is: {test_prep_perc}")
else:
    print(f"Students who completed test prepration courses are doing \"BAD\" their % is: {test_prep_perc}")

"""#3.    What is the impact of parent education in student performance good, bad, or no impact."""



def per_edu_effect(records, labels):
    perc = [0,0]
    scores = [0,0]
    count = [0,0]
    index_parent_ed = labels.index('parental level of education')
    for r in records:
        if r[index_parent_ed] == "master's degree":
            #Index 0 for records of child with parents having a master's degree
            scores[0] += sum([int(i) for i in r[-3:]])
            count[0] += 3
        else:
            #Index 01 for records of child with parents without a master's degree
            scores[1] += sum([int(i) for i in r[-3:]])
            count[1] += 3
    for i in range(len(perc)):
        perc[i] = round(float(scores[i]/count[i]),2)
    return perc

P_Masters, P_Without_Masters = per_edu_effect(data, labels)
delta = P_Masters - P_Without_Masters

if delta > 5:
    print("Master degree has good impact")
elif delta < -5:
    print("Master's degree of a parent has bad impact")
else:
    print("Master's degree is irrelevant")

