# -*- coding: utf-8 -*-
"""Cows_and_Bulls.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ds50LoOWxgNG05S0LDBk3iEQrpKdlvMm

# Cows And Bulls
"""

"""
Create a program that will play the “cows and bulls” game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. 
For every digit that the user guessed correctly in the correct place, they have a “cow”. 
For every digit the user guessed correctly in the wrong place is a “bull.” 
Every time the user makes a guess, tell them how many “cows” and “bulls” they have. 
Once the user guesses the correct number, the game is over. 
Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls 
  # {1,3 as cow}
  >>> 1286
  1 cow, 1 bull 
  # {1 as cow}, {8 as bull}
  ...

  Number may contain duplicate digits
  

"""


import random as ra
from sys import exit


def count_cows(org,inp):
    return len([a for a in range(len(inp)) if org[a] == inp[a]])


def count_bulls(org,inp):
    """
    first Remove all the matching pairs
    """
    for a in range(len(org)):
        if org[a] == inp[a]:
            org = org.replace(org[a],"x",1)
            inp = inp.replace(inp[a],"x",1)
    org = org.replace("x","")
    inp = inp.replace("x","")

    """
    Now count if input digit is present on a different index
    if present, we found a bull, mark the first intance of original value with "x"
    """
    
    c = 0
    for i in range(len(org)):
        if inp[i] in org :
            c += 1
            org = org.replace(inp[i],"x",1)
    return c


def get_input():
    try:
        print("Guess a number between [1000 - 9999]")
        print("Enter \"q\" to quit")
        raw_in = input()
        num = int(raw_in)
    except:
        if(raw_in == "q"):
            exit
            quit
            exit()
        print("Invalid input format!")
        return 0
    if(num > 9999 or num < 1000):
        print("Number is not from valid interval.")
        return 0
    return num

if __name__=="__main__":
    Tries = 0
    To_guess = ra.randint(1000,9999)
    try:
        while True:
            while True:
                user_input = get_input()
                Tries += 1
                if(user_input):
                    break

            if(user_input == To_guess):
                print(f"Yes! the number is {To_guess}. Total tries: {Tries}")
                break

            cows = count_cows(str(To_guess),str(user_input))
            bulls = count_bulls(str(To_guess),str(user_input))
            print(f"cows: {cows} bulls: {bulls}")

    except:
        print("Game Over")

